name = 'office-user-auto-create'
account_id = ''
type = 'webpack'
workers_dev = true
webpack_config = 'webpack.config.js'

[vars]
_ANNOUNCEMENT = 'some announcement'
_GET_CODE_LINK = 'https://some.link'
_AAD_CONFIG = '{ "tenantId": "", "clientId": "", "clientSecret": "" }'
_OFFICE_DOMAINS = '["domain1.com", "domain2.org"]'
_OFFICE_SUBSCRIPTIONS = '[{ "name": "subscription 1", "sku": "skuid" }, { "name": "subscription 2", "sku": "skuid" }]'
_USERNAME_BLACKLIST = '["admin", "gay"]'
_GENERATE_CODES_PATH_SECRET = 'some_secret'
